######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 18 01:38:34 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qt debug

# Input
HEADERS += student.h version.h versionlist.h studentlist.h
SOURCES += main.cpp student.cpp version.cpp versionlist.cpp studentlist.cpp
